### ISSUE TITLE
Why do we check the content for utf8 bit ?

### ISSUE THREAD

**Issue by celogeek** [PerlRedis/perl-redis#107]
Hi,

I see that in the code : 
```
utf8::downgrade($bin, 1)
or croak "command sent is not an octet sequence in the native encoding (Latin-1). Consider using debug mode to see the command itself.";
```

This check all content we pass for utf8 bit code, and then croak if anything is found.

Many tools now fail with that check (on our company), and I wonder why do we care about what we put inside Redis ?
Can't we just let the user deal with it ?

**Comment by vsespb** [comment]
See #95

**Comment by dams** [comment]
Vincent,

Tell us more about how your tools "now fail with that check". If you can show the problem with a minimal example, the better.

dams.

Victor Efimov wrote:

**Comment by celogeek** [comment]
Yeah, I have seen the thread. What a mess.

You know we crawl website, and we receive string encoded with sometime utf8 or may be sometime something else.

This is pass directly to redis, like :

```
my $term = "\x{ffff}";
$redis->set($key, $term);
```

So I may automatically downgrade any string that come thru or just retry by downgrading in case that this error show up.

I will try to figure out the bug exactly, try to reproduce, and see if I can find a good way to handle it without changing too much code or breaking too much legacy code.

**Comment by vsespb** [comment]
I believe you misunderstand perl unicode string concept somewhere.

The only way this

```
my $term = "\x{ffff}";
$redis->set($key, $term);
```

could work is when Redis.pm will save UTF-8 flag together with data (i.e. save additional data, make it incompatible with other Redis clients).

Other ways you want this to work are broken. They could work for you, but they all contradict perl unicode model and can cause bugs for other users.

> You know we crawl website, and we receive string encoded with sometime utf8 or may be sometime something else

I think you need to
1) decide how to treat data - as binary or as text.
2) Understand what HTTP library returns - binary or text
3) If you want binary data, force library to return binary (because low level protocols are binary data), if you want text but library returns binary - decode it to text using web page Charset/Meta headers.
4) If you want to store text in Redis, encode it to one encoding (i.e. UTF8) using Encode::encode (not "utf8::downgrade")

**Comment by celogeek** [comment]
I have handle the error message, just for the bad tools, that automatically encode string with not Latin1 char. So ok, thanks for clarification. I close this.
